apiVersion: v1
kind: ConfigMap
metadata:
  name: theatre-config
  labels:
    app: showbuzz-theatre-service
data:
  PORT: "3002"
  MONGO_URL: "mongodb+srv://anirudhjagath2002:773D7AN3YuThj5A4@cluster0.thmadpi.mongodb.net/showbuzz-theatre?retryWrites=true&w=majority&appName=Cluster0"
  EMAIL: "tickerpage@gmail.com"
  PASSWORD: "vfte pvyn gvat uylk"
  ACCESS_TOKEN_SECRET: "frstgbsrtdvdcaerfvthtybsadvdfbvdfbdbf"