name: Build & Publish auth service Docker Image

on:
    push:
        branches: [ 'main' ]
        paths:
            - "auth-service/**"

jobs:
    push_to_registry:
        name: Push Docker Image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v3

            - name: Login to Docker Hub
              uses:  docker/login-action@v2
              with:
                username: ${{ secrets.USERNAME}}
                password: ${{ secrets.PASSWORD}}

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                context:  ./user/
                push: true
                tags: anirudhjagath/showbuzz-auth-service:latest